 USE iscanner;
CREATE TABLE passengers(
UserId INT(30) AUTO_INCREMENT PRIMARY KEY,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL,
phone VARCHAR(20) NOT NULL,
Address VARCHAR(200) NOT NULL,
City VARCHAR(30) NOT NULL,
County VARCHAR(30) NOT NULL,
Country VARCHAR(30) NOT NULL,
ZipCode VARCHAR(30) NOT NULL
); 
select* from passengers;
